name: 'Run Playtests'

on:
  workflow_dispatch:
    inputs:
      deck_1:
        description: Deck
        type: string
        required: true
        default: 'prinny/forge/complete/absol.dck'
      rounds:
        description: Rounds
        type: string
        required: true
        default: '7'
  workflow_call:
    inputs:
      deck_1:
        description: Deck
        type: string
        required: true
      rounds:
        description: Rounds
        type: string
        required: true
        default: '7'
      error_on_loss:
        description: Throw error on match loss
        type: string
        default: 'false'

permissions:
  id-token: write
  contents: read

jobs:
  cache:
    name: 'Build cache'
    uses: ./.github/workflows/cache.yml

  sanitize:
    name: Sanitize
    runs-on: ubuntu-latest
    outputs:
      deck_1: ${{ steps.sanitize.outputs.deck_1 }}
      rounds: ${{ steps.sanitize.outputs.rounds }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sanitize inputs
        id: sanitize
        run: |
          if [ ! -f "${{ inputs.deck_1 }}" ]; then echo "${{ inputs.deck_1 }} not found"; exit 1; fi
          deck_1=$(echo '${{ inputs.deck_1 }}' | sed -r 's/^.+\/([^\/]+)\.dck$/\1/')
          echo "deck_1=${deck_1}" >> $GITHUB_OUTPUT

          rounds="$(( ${{ inputs.rounds }} + 0 ))"
          if [[ "$rounds" -lt 1 ]]; then echo "Rounds is $rounds"; exit 1; fi
          echo "rounds=${rounds}" >> $GITHUB_OUTPUT

  decks:
    name: Get the playtest decks
    runs-on: ubuntu-latest
    outputs:
      list: ${{ steps.decks.outputs.list }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get deck list
        id: decks
        working-directory: playtest
        run: |
          echo 'list={"deck_2": ["'$(ls *.dck | sed -r 's/\.dck$//' | tr '\n' ' ' | sed -r 's/ $//' | sed -r 's/ /","/g')'"]}' >> $GITHUB_OUTPUT

  playtest:
    name: 'Playtest ${{ needs.sanitize.outputs.deck_1 }} vs. ${{ matrix.deck_2 }} (${{ needs.sanitize.outputs.rounds }}x)'
    needs: [cache, sanitize, decks]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.decks.outputs.list) }}
    uses: ./.github/workflows/simulation.yml
    with:
      deck_1: '${{ inputs.deck_1 }}'
      deck_2: 'playtest/${{ matrix.deck_2 }}.dck'
      rounds: '${{ inputs.rounds }}'
      error_on_loss: '${{ inputs.error_on_loss || 'false' }}'

  error:
    if: failure()
    name: Check for playtest losses
    needs: [cache, sanitize, decks, playtest]
    runs-on: ubuntu-latest
    steps:
      - name: Return error on failure
        run: exit 1
