name: '[Run Playtests on PR]'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'decks/**.dck'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  id-token: write
  contents: read

jobs:
  cache:
    name: 'Build cache'
    uses: ./.github/workflows/cache.yml

  decks:
    name: Get the updated decks
    runs-on: ubuntu-latest
    outputs:
      list: ${{ steps.decks.outputs.list }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Get deck list
        id: decks
        run: |
          echo 'list={"deck_1": ["'$(echo -ne $(git --no-pager diff --name-only ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }} -- | grep '\.dck') | sed -r 's/ /","/g')'"]}' >> $GITHUB_OUTPUT

  playtest:
    name: 'Playtest ${{ matrix.deck_1 }}'
    needs: [cache, decks]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.decks.outputs.list) }}
    uses: ./.github/workflows/playtest.yml
    with:
      deck_1: '${{ matrix.deck_1 }}'
      rounds: '7'
      error_on_loss: 'true'

  error:
    if: failure()
    name: Check for all losses
    needs: [cache, decks, playtest]
    runs-on: ubuntu-latest
    steps:
      - name: Return error on failure
        run: exit 1
