name: 'Run Simulation'

on:
  workflow_dispatch:
    inputs:
      deck_name_player:
        description: Player deck name
        type: string
        required: true
        default: 'absol'
      deck_file_player:
        description: Player deck file
        type: string
        required: true
        default: 'decks/prinny/forge/complete/absol.dck'
      deck_name_opponent:
        description: Opponent deck name
        type: string
        required: true
        default: 'altaria'
      deck_file_opponent:
        description: Opponent deck file
        type: string
        required: true
        default: 'decks/prinny/forge/complete/altaria.dck'
      rounds:
        description: Rounds
        type: string
        required: true
        default: '7'
      wins_required:
        description: Wins required
        type: string
        default: '0'
  workflow_call:
    inputs:
      deck_name_player:
        description: Player deck name
        type: string
        required: true
      deck_file_player:
        description: Player deck file
        type: string
        required: true
      deck_name_opponent:
        description: Opponent deck name
        type: string
        required: true
      deck_file_opponent:
        description: Opponent deck file
        type: string
        required: true
      rounds:
        description: Rounds
        type: string
        required: true
        default: '7'
      wins_required:
        description: Wins required
        type: string
        required: true
        default: '0'
    outputs:
      deck_name_player:
        value: '${{ jobs.sim.outputs.deck_name_player }}'
      score_player:
        value: '${{ jobs.sim.outputs.score_player }}'
      deck_name_opponent:
        value: '${{ jobs.sim.outputs.deck_name_opponent }}'
      score_opponent:
        value: '${{ jobs.sim.outputs.score_opponent }}'

permissions:
  id-token: write
  contents: read

env:
  FORGE_SNAPSHOT_URL: 'https://downloads.cardforge.org/dailysnapshots/'
  HOME: '/home/runner'

jobs:
  sim:
    name: 'Simulate ${{ inputs.deck_name_player }} vs. ${{ inputs.deck_name_opponent }} (${{ inputs.rounds }}x)'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Game info
        id: game
        run: |
          rounds="$(( ${{ inputs.rounds }} + 0 ))"
          if [ "$rounds" -lt 1 ]; then echo "Rounds is $rounds"; exit 1; fi
          echo "rounds=${rounds}" >> $GITHUB_OUTPUT

          wins_required="$(( ${{ inputs.wins_required }} + 0 ))"
          if [ "$wins_required" -lt 0 ] || [ "$wins_required" -gt "$rounds" ]; then echo "Wins required is $wins_required"; exit 1; fi
          echo "wins_required=${wins_required}" >> $GITHUB_OUTPUT

      - name: Get player deck file
        run: |
          if [ ! -f "${{ inputs.deck_file_player }}" ]; then echo "${{ inputs.deck_file_player }} not found"; exit 1; fi

      - name: Get opponent deck file
        run: |
          if [ ! -f "${{ inputs.deck_file_opponent }}" ]; then echo "${{ inputs.deck_file_opponent }} not found"; exit 1; fi

      - name: 'Cache setup'
        id: cache-forge
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.HOME }}/forge
          key: forge
          restore-keys: forge

      - name: 'Get download info'
        id: version
        if: steps.cache-forge.outputs.cache-hit != 'true'
        run: |
          echo "name=$(curl -s ${{ env.FORGE_SNAPSHOT_URL }} | grep -oE '"forge-desktop.+\.jar"' | sed -r 's/"//g')" >> $GITHUB_OUTPUT

      - name: 'Install Forge'
        if: steps.cache-forge.outputs.cache-hit != 'true'
        working-directory: ${{ env.HOME }}
        run: |
          echo "INSTALL_PATH=forge" > forge_latest.properties
          curl -s ${{ env.FORGE_SNAPSHOT_URL }}${{ steps.version.outputs.name }} -o ./${{ steps.version.outputs.name }}
          java -jar ./${{ steps.version.outputs.name }} -options forge_latest.properties

      - name: 'Get jar file name'
        id: jar
        working-directory: ${{ env.HOME }}/forge
        run: |
          echo "name=$(ls forge-gui-desktop-*.jar)" >> $GITHUB_OUTPUT

      - name: 'Symlink deck path'
        run: |
          mkdir -p $HOME/.forge/decks
          rm -f $HOME/.forge/decks/constructed && ln -s $HOME/work/comes-in-tapped/comes-in-tapped $HOME/.forge/decks/constructed

      - name: 'Run simulation'
        working-directory: ${{ env.HOME }}/forge
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          java -Xmx4096m -Dfile.encoding=UTF-8 -jar ${{ steps.jar.outputs.name }} sim -d "${{ inputs.deck_file_player }}" "${{ inputs.deck_file_opponent }}" -n ${{ steps.game.outputs.rounds }}

      - name: 'Upload full log'
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: '${{ inputs.deck_name_player }}-${{ inputs.deck_name_opponent }}-forge.log'
          path: ${{ env.HOME }}/.forge/forge.log

      - name: 'Get match results'
        id: results
        run: |
          line=$(grep '^Match result: ' $HOME/.forge/forge.log | tail -n 1)
          echo $line

          deck_1=$(echo $line | sed -r 's/^[^-]+-([^:]+): ([0-9]+) [^-]+-([^:]+): ([0-9]+) *$/\1/')
          score_1=$(echo $line | sed -r 's/^[^-]+-([^:]+): ([0-9]+) [^-]+-([^:]+): ([0-9]+) *$/\2/')
          deck_2=$(echo $line | sed -r 's/^[^-]+-([^:]+): ([0-9]+) [^-]+-([^:]+): ([0-9]+) *$/\3/')
          score_2=$(echo $line | sed -r 's/^[^-]+-([^:]+): ([0-9]+) [^-]+-([^:]+): ([0-9]+) *$/\4/')

          if [ "$deck_1" == "${{ inputs.deck_name_player }}" ];
          then
            echo "deck_player=$deck_1" >> $GITHUB_OUTPUT
            echo "score_player=$score_1" >> $GITHUB_OUTPUT
            echo "deck_opponent=$deck_2" >> $GITHUB_OUTPUT
            echo "score_opponent=$score_2" >> $GITHUB_OUTPUT
          else
            echo "deck_player=$deck_2" >> $GITHUB_OUTPUT
            echo "score_player=$score_2" >> $GITHUB_OUTPUT
            echo "deck_opponent=$deck_1" >> $GITHUB_OUTPUT
            echo "score_opponent=$score_1" >> $GITHUB_OUTPUT
          fi

      - name: '${{ steps.results.outputs.deck_player }} won ${{ steps.results.outputs.score_player }} of ${{ steps.game.outputs.rounds }} (Required wins: ${{ steps.game.outputs.wins_required }})'
        run: |
          if [ "${{ steps.results.outputs.score_player }}" -lt "${{ steps.game.outputs.wins_required }}" ];
          then
            echo "You just lost the game"
            exit 1
          fi
